---
title: "About Me"
format:
  html:
    body-class: about-page
---

## Currently

Data Engineer at Medical College of Wisconsin, where I build data pipelines and infrastructure to support healthcare analytics and research.

-   Involvements: [AN.ai Lab](https://www.anailab.com/our-team/bhabishya-neupane), Seo Lab

## Past Experiences

**Ecolab**, *Product Data* *Analyst*\
- Developed data-driven solutions for operational efficiency and business intelligence.

[**Bureau of Business Research**](https://business.unl.edu/research/bureau-business-research/academic-research/bbr-scholars/), *Research Analyst*\
- Conducted economic research and statistical analysis.

## Research Publications

-   **Journal of Clinical Oncology (2025)**
    -   [Association Between Area Deprivation Index and Survival in Patients With Advanced Biliary Tract Cancers](https://ascopubs.org/doi/abs/10.1200/JCO.2025.43.4_suppl.710)
-   **bioRxiv (2025)**
    -   [CHIMERA-DDR: A Machine Learning Framework for Classifying Heterogeneous Mismatch-Repair and Homologous-Recombination Deficiency Patterns in Prostate Cancer](https://www.biorxiv.org/content/10.1101/2025.10.08.680958v2.abstract)
    -   [Moving Beyond Binary Biomarkers: Machine Learning Model Resolves Concurrent and Molecularly Heterogeneous Mismatch-Repair and Homologous-Recombination Deficiencies in Prostate Cancer](https://www.biorxiv.org/content/biorxiv/early/2025/10/14/2025.10.08.680958.full.pdf)
-   **JAMA Surgery (2024)**
    -   [Applying Large Language Models for Surgical Case Length Prediction](https://jamanetwork.com/journals/jamasurgery/article-abstract/2835953)
-   **Surgery (2024)**
    -   [Development and validation of an artificial intelligence system for surgical case length prediction](https://www.sciencedirect.com/science/article/pii/S003960602400919X)

## Education

University of Nebraska-Lincoln - B.A. Economics & Mathematics

## Get in Touch

Feel free to connect with me:

-   Website: [bhabishya.rbind.io](https://bhabishya.rbind.io/)
-   Email: bhabishyaneupane45\@gmail.com
-   GitHub: [github.com/nBhabish](https://github.com/nBhabish)
